import { mkdir } from "node:fs/promises";
import { join } from "node:path";
import type { AssetMetadata } from "@shopclip/shared";

import { mediaOutputDir } from "./mediaPaths.js";
import { resolveFfmpegCommand, runMediaCommand } from "./mediaTooling.js";
import {
  createSpeechToTextProviderFromEnv,
  type SpeechToTextProvider,
} from "../../providers/asr/speechToTextProvider.js";

export interface ExtractedAudioSummary {
  audioPath?: string;
  asrSummary: string;
  transcript: string;
}

export interface AudioExtractionOptions {
  outputDir?: string;
  speechProvider?: SpeechToTextProvider;
}

const stringFromMetadata = (metadata: Record<string, unknown> | undefined, key: string) => {
  const value = metadata?.[key];
  return typeof value === "string" && value.trim() ? value.trim() : undefined;
};

const sourcePathForAsset = (asset: AssetMetadata): string | undefined =>
  stringFromMetadata(asset.metadata, "localFilePath") || (asset.url.startsWith("/api/") ? undefined : asset.url);

const sanitizeSegment = (value: string): string =>
  value.replace(/[^a-z0-9-]+/gi, "-").replace(/^-+|-+$/g, "").toLowerCase() || "asset";

export const extractAssetAudioSummary = async (
  asset: AssetMetadata,
  options: AudioExtractionOptions = {},
): Promise<ExtractedAudioSummary> => {
  if (asset.type !== "video") {
    return {
      asrSummary: "",
      transcript: "",
    };
  }

  const sourcePath = sourcePathForAsset(asset);
  if (!sourcePath) {
    throw new Error(`Cannot extract real audio for asset ${asset.id}: no local file path or direct media URL.`);
  }

  const outputDir = options.outputDir ?? join(mediaOutputDir(), asset.id, "audio");
  await mkdir(outputDir, { recursive: true });
  const audioPath = join(outputDir, `${sanitizeSegment(asset.id)}.m4a`);
  const command = await resolveFfmpegCommand();
  await runMediaCommand(command, [
    "-y",
    "-i",
    sourcePath,
    "-vn",
    "-ac",
    "1",
    "-ar",
    "16000",
    "-c:a",
    "aac",
    audioPath,
  ]);

  const speechProvider = options.speechProvider ?? createSpeechToTextProviderFromEnv();
  if (speechProvider) {
    const asr = await speechProvider.transcribe({ audioPath });
    return {
      audioPath,
      asrSummary: `Transcript generated by ${asr.provider}.`,
      transcript: asr.transcript,
    };
  }

  return {
    audioPath,
    asrSummary: `Audio extracted from ${asset.name}; ASR provider is not configured.`,
    transcript: "",
  };
};
