import { spawn } from "node:child_process";
import { createRequire } from "node:module";
import { mkdtemp, rm, stat } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import type { AssetMetadata } from "@shopclip/shared";

import { extractAssetAudioSummary } from "./audioExtractor.js";
import { sampleAssetFrames } from "./frameSampler.js";
import { probeAssetMedia } from "./mediaProbe.js";

const require = createRequire(import.meta.url);
const ffmpegPath = (require("@ffmpeg-installer/ffmpeg") as { path: string }).path;

const workdirs: string[] = [];
const REAL_MEDIA_TEST_TIMEOUT_MS = 15_000;

const runFfmpeg = (args: string[]) =>
  new Promise<void>((resolve, reject) => {
    const child = spawn(ffmpegPath, args, { windowsHide: true });
    let stderr = "";
    child.stderr.on("data", (chunk) => {
      stderr += String(chunk);
    });
    child.once("error", reject);
    child.once("close", (code) => {
      if (code === 0) {
        resolve();
        return;
      }
      reject(new Error(`ffmpeg fixture generation failed with ${code}: ${stderr.slice(0, 800)}`));
    });
  });

const createFixtureVideo = async () => {
  const directory = await mkdtemp(join(tmpdir(), "shopclip-real-media-"));
  workdirs.push(directory);
  const videoPath = join(directory, "fixture.mp4");
  await runFfmpeg([
    "-y",
    "-f",
    "lavfi",
    "-i",
    "testsrc=size=160x90:rate=5",
    "-f",
    "lavfi",
    "-i",
    "sine=frequency=1000:duration=1.2",
    "-t",
    "1.2",
    "-c:v",
    "mpeg4",
    "-q:v",
    "5",
    "-c:a",
    "aac",
    videoPath,
  ]);
  return { directory, videoPath };
};

const removeWorkdir = async (directory: string) => {
  for (let attempt = 0; attempt < 5; attempt += 1) {
    try {
      await rm(directory, { recursive: true, force: true });
      return;
    } catch (error) {
      if (
        attempt === 4 ||
        !(error instanceof Error) ||
        !("code" in error) ||
        error.code !== "EBUSY"
      ) {
        throw error;
      }
      await new Promise((resolve) => setTimeout(resolve, 100 * (attempt + 1)));
    }
  }
};

const assetForVideo = (videoPath: string): AssetMetadata => ({
  id: "asset-real-video",
  projectId: "project-real-video",
  type: "video",
  status: "uploaded",
  source: "public_reference",
  url: videoPath,
  name: "fixture.mp4",
  mimeType: "video/mp4",
  sizeBytes: 1000,
  tags: ["real", "video"],
  metadata: {
    localFilePath: videoPath,
  },
});

describe("real media processing", () => {
  afterEach(async () => {
    await Promise.all(workdirs.splice(0).map(removeWorkdir));
  });

  it("probes, extracts real frames, and extracts real audio from a video file", async () => {
    const { directory, videoPath } = await createFixtureVideo();
    const asset = assetForVideo(videoPath);

    const probe = await probeAssetMedia(asset);
    expect(probe.durationSeconds).toBeGreaterThan(1.1);
    expect(probe.width).toBe(160);
    expect(probe.height).toBe(90);

    const frames = await sampleAssetFrames(asset, probe, {
      outputDir: join(directory, "frames"),
      publicBaseUrl: "https://assets.example.test/frames",
    });
    expect(frames.length).toBeGreaterThanOrEqual(2);
    expect(frames[0]?.key).toMatch(/^https:\/\/assets\.example\.test\/frames\/asset-real-video-frame-/);
    await expect(stat(frames[0]!.localPath!)).resolves.toMatchObject({ size: expect.any(Number) });

    const audio = await extractAssetAudioSummary(asset, {
      outputDir: join(directory, "audio"),
    });
    expect(audio.asrSummary).not.toContain("Mock ASR summary");
    expect(audio.transcript).toBe("");
    expect(audio.asrSummary).toContain("ASR provider is not configured");
    expect(audio.audioPath).toMatch(/asset-real-video\.m4a$/);
    await expect(stat(audio.audioPath!)).resolves.toMatchObject({ size: expect.any(Number) });
  }, REAL_MEDIA_TEST_TIMEOUT_MS);

  it("uses an injected real speech provider after extracting audio", async () => {
    const { directory, videoPath } = await createFixtureVideo();
    const asset = assetForVideo(videoPath);

    const audio = await extractAssetAudioSummary(asset, {
      outputDir: join(directory, "audio-provider"),
      speechProvider: {
        transcribe: async ({ audioPath }) => {
          await expect(stat(audioPath)).resolves.toMatchObject({ size: expect.any(Number) });
          return {
            provider: "test-real-asr",
            transcript: "real transcript from extracted audio",
          };
        },
      },
    });

    expect(audio.asrSummary).toBe("Transcript generated by test-real-asr.");
    expect(audio.transcript).toBe("real transcript from extracted audio");
  }, REAL_MEDIA_TEST_TIMEOUT_MS);
});
